from __future__ import annotations

from pathlib import Path

import numpy as np
import pandas as pd

from .config import RunConfig
from .paths import dissertation_root


def write_group_summary(descriptors: pd.DataFrame, out_path: Path) -> None:
    accepted = descriptors[descriptors["status"] == "accepted"].copy()
    if accepted.empty:
        pd.DataFrame().to_csv(out_path, index=False)
        return

    rows = []
    for source, grp in accepted.groupby("source"):
        row = {
            "source": source,
            "n_accepted": len(grp),
            "alpha_dfa_mean": float(grp["alpha_dfa"].mean()),
            "alpha_dfa_std": float(grp["alpha_dfa"].std(ddof=0)),
            "alpha_dfa_median": float(grp["alpha_dfa"].median()),
        }
        if "alpha_width" in grp.columns:
            aw = grp["alpha_width"].dropna()
            row["alpha_width_mean"] = float(aw.mean()) if len(aw) else np.nan
        rows.append(row)

    pd.DataFrame(rows).to_csv(out_path, index=False)


def write_dissertation_summaries(cfg: RunConfig, descriptors: pd.DataFrame, quality: pd.DataFrame) -> None:
    root = dissertation_root(cfg)
    root.mkdir(parents=True, exist_ok=True)

    accepted = descriptors[descriptors["status"] == "accepted"].copy()
    cols = [
        "track_id",
        "source",
        "year",
        "position",
        "artist",
        "title",
        "alpha_dfa",
        "alpha_width",
        "alpha_peak",
        "spectrum_skew",
        "mfdfa_ok",
        "contour_length",
    ]
    cols = [c for c in cols if c in accepted.columns]
    accepted[cols].to_csv(root / "f0_fractal_summary.csv", index=False)

    if not quality.empty:
        qcols = [
            "track_id",
            "source",
            "year",
            "position",
            "status",
            "selected_duration_sec",
            "raw_voiced_coverage",
            "selected_voiced_coverage",
            "median_voiced_prob",
            "jump_rate",
            "octave_jump_rate",
            "skip_reason",
        ]
        qcols = [c for c in qcols if c in quality.columns]
        quality[qcols].to_csv(root / "f0_quality_summary.csv", index=False)

    readme = root / "README.md"
    readme.write_text(
        """# Audio-Melody F0 Fractal Summaries

Portable dissertation-ready summaries from Billboard audio-melody F0 pipeline.

## Files

- `f0_fractal_summary.csv` — accepted tracks with DFA/MFDFA descriptors
- `f0_quality_summary.csv` — F0 extraction and contour-cleaning QA metrics

## Provenance

Generated by `server_handoff/billboard_audio_melody_f0` Stage 2 (`--output-scope full`).
Input: vocal stems + librosa PYIN F0 + vendored fractal `compute_fractal_descriptors_1d`.
""",
        encoding="utf-8",
    )
